(source gnu)
(source marmalade)
(source melpa)

(depends-on "cask")
(depends-on "dictionary")
(depends-on "httpcode")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "seq")
(depends-on "slime")
(depends-on "switch-window")
(depends-on "wgrep-ag")
(depends-on "xkcd")
