(mapc (lambda (auto-mode)
        (add-to-list 'auto-mode-alist auto-mode))
      '(("Cask$"             . lisp-interaction-mode)
        ("hosts$"            . conf-mode)
        ("\\.mdwn$"          . markdown-mode)
        ("\\.mdtxt$"         . markdown-mode)
        ("\\.mkd$"           . markdown-mode)
        ("\\.mkdn$"          . markdown-mode)
        ("\\mdwn$"           . markdown-mode)
        ("\\.zsh$"           . shell-script-mode)
        ("\\.html?\\'"       . web-mode)
        ("\\.erb$"           . web-mode)))

(provide 'my-mode-mappings)
