(mapc (lambda (auto-mode)
        (add-to-list 'auto-mode-alist auto-mode))
      '(("Brewfile"        . conf-unix-mode)
        (".builder$"       . enh-ruby-mode)
        ("\\.gemspec$"     . enh-ruby-mode)
        ("\\.podspec$"     . enh-ruby-mode)
        ("\\.rake$"        . enh-ruby-mode)
        ("\\.rb$"          . enh-ruby-mode)
        ("\\.ru$"          . enh-ruby-mode)
        ("\\.thor$"        . enh-ruby-mode)
        ("/\\(?:Gem\\|Rake\\|Cap\\|Thor\\|Vagrant\\|Guard\\|Pod\\)file\\'" . enh-ruby-mode)
        ("\\.mdwn$"        . markdown-mode)
        ("\\.mdtxt$"       . markdown-mode)
        ("\\.mkd$"         . markdown-mode)
        ("\\.mkdn$"        . markdown-mode)
        ("\\mdwn$"         . markdown-mode)
        ("\\.zsh$"         . shell-script-mode)
        ("\\.html?\\'"     . web-mode)
        ("\\.erb$"         . web-mode)))

(provide 'my-mode-mappings)
